### ISSUE TITLE
Latitude and Longitude fields reset on click out

### ISSUE THREAD

**Issue by al-lad** [AutoDarkMode/Windows-Auto-Night-Mode#295]
In the settings tab, I'm trying to set a latitude and longitude different from zero, but every time I type/paste a value in a field, then click on the other field to do the same, the first field resets to zero. The button "apply coordinates" also resets the values to zero before submitting, and then is grayed out.

![image](https://user-images.githubusercontent.com/76215778/136646914-8305d467-7191-4390-a8b2-bcb240b2f6df.png)

**Comment by Spiritreader** [comment]
Could you do me a favor and test if setting the coordinates manually works?

- Open the App
- Go to Settings
- Scroll down to the "Config" section
- Click on "Open config file"
- **Close** the Auto Dark Mode App
- Put in your coordinates in the "Location" section here:
![image](https://user-images.githubusercontent.com/18438899/136650956-25c3dc58-d1cd-46cb-8e0e-7bdf46888d2c.png)
- **Save** the config file
- Start the app again and check if the values have been loaded correctly

**Comment by al-lad** [comment]
yeah, that worked : 

![image](https://user-images.githubusercontent.com/76215778/136653555-5355e794-7cf4-4725-9282-03bf7d13f3a7.png)

**Comment by cmhrky** [comment]
It's like this in Turkish. We need to enter with a comma.

**Comment by al-lad** [comment]
It is indeed working with a comma. If I put a value with a dot, it just reverts to the last stored value (so not necessarily zero) with a comma.

**Comment by NoeDeMontard** [comment]
It seams that negative coordinates are striped of their sign. I'm on commit 038cde2 with locale FR.

**Comment by Spiritreader** [comment]
fixed in 7a0ef6c3

**Comment by Spiritreader** [comment]
> I have another weird behavior I detected going back to negative coordinate from using the coordinate + 360 to have a positive one. The times are not exactly the same after this modification. For example, there is a table :
> 
> Latitude	Longitude	Light	Dark
> 0	0	07:42	19:48
> 0	360	07:42	19:49
> 45	0	08:17	19:13
> 45	360	07:16	19:15
> I suppose it might be that by adding 360 it use the information for tomorrow.

That's not an issue or weird behavior. A longitude of 360 doesn't exist.
You will only get correct results if you enter a valid lan/lot combination on the globe.

https://stackoverflow.com/a/16743805/12824055

**Comment by NoeDeMontard** [comment]
Well, yes a longitude shouldn't be out of the ]-180 +180] range, and I only used a value outside of it because I couldn't input negative value. But as it is really just an angle, the angle is still the same (without counting turns) if you add 360.

I would say that it could have returned an error or a totally invalid value by saying it isn't in the allowed range, but the fact that it's so close but not the same made me think it's kind of handled by the method you use but with that weird effect that I tough I could report as I was here.

That said, I agree it's not in the normal range and cause a problematic behavior (seeing it doesn't crash the app and even give an answer close to the one with the equivalent angle within the standard range) so it's not something you have to investigate and "fix".

I would say that what might be more of an issue then is the fact that an input outside of the range might be a symptom of a misplaced or missing decimal dot, and even that would just make the times incorrect for the place just as another typing mistake might.

**Comment by Spiritreader** [comment]
> Well, yes a longitude shouldn't be out of the ]-180 +180] range, and I only used a value outside of it because I couldn't input negative value. But as it is really just an angle, the angle is still the same (without counting turns) if you add 360.
> 
> I would say that it could have returned an error or a totally invalid value by saying it isn't in the allowed range, but the fact that it's so close but not the same made me think it's kind of handled by the method you use but with that weird effect that I tough I could report as I was here.
> 
> That said, I agree it's not in the normal range and cause a problematic behavior (seeing it doesn't crash the app and even give an answer close to the one with the equivalent angle within the standard range) so it's not something you have to investigate and "fix".
> 
> I would say that what might be more of an issue then is the fact that an input outside of the range might be a symptom of a misplaced or missing decimal dot, and even that would just make the times incorrect for the place just as another typing mistake might.

I have addressed this by putting a hard limit on lat/lon, such that values exceeding the limits are auto corrected to their maximum. 
If for whatever reason people still want to use ranges beyond the defined limits, they can still do so by modifying the config file.
